

name: Deploy FastAPI internship project
on:
  push:
    branches: [ be-20-deploy ]
  pull_request:
    branches: [ be-20-deploy ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
                   
      - name: Lint code
        run: echo "Linting repository!"

      - name: Run unit tests
        run: |
          echo "Running unit tests"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create .env 
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-app-php
          IMAGE_TAG: latest
        run: |
          docker build -t fast_api_deploy_repository .
          docker tag fast_api_deploy_repository:latest 195766531418.dkr.ecr.us-east-1.amazonaws.com/fast_api_deploy_repository:latest
          docker push 195766531418.dkr.ecr.us-east-1.amazonaws.com/fast_api_deploy_repository:latest
          echo "::set-output name=image::195766531418.dkr.ecr.us-east-1.amazonaws.com/fast_api_deploy_repository:latest"

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition fastapi_definition \
          --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: fastapiproject
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: fast_api_service
          cluster: fastapi_cluster
          wait-for-service-stability: true
